name: EmojiChat
version: '${project.version}'
main: org.coleski123.emojichat.EmojiChat
api-version: 1.20
commands:
  emoji:
    description: Shows you all the current emojis.
    usage: /emoji list
permissions:
  emojichat.use:
    description: Allows the player to access emoji chat.
    default: op
