name: EmojiChat
version: 0.8
main: org.coleski123.emojichat.EmojiChat
api-version: 1.20
commands:
  emojilist:
    description: Shows you all the current emojis.
    usage: /emojilist
  emojisave:
    description: Saves the EmojiChat config
    usage: /emojisave
permissions:
  emojichat.use.chat:
    description: Allows the player to access emojis in chat.
    default: op
  emojichat.use.saveconfig:
    description: Allows the player to save the EmojiChat config.
    default: op
  emojichat.use.list:
    description: Allows the player to use /emojilist
    default: op
  emojichat.use.signs:
    description: Allows the usage of emojis on signs
    default: op
  emojichat.use.books:
    description: Allows the usage of emojis in books
    default: op
